### ISSUE TITLE
Script not running (Permission denied)

### ISSUE THREAD

**Issue by cyber-jack** [stealthcopter/deepce#1]
Hi

I downloaded the script as outlined in your README using "wget https://github.com/stealthcopter/deepce/raw/master/deepce.sh"

When trying to run the script, I get "bash: ./deepce.sh: Permission denied"

Please help

**Comment by stealthcopter** [comment]
@cyber-jack Just need to run `chmod +x ./deepce.sh` on the script to make it executable. I will update the documentation to reflect this. Thanks for the report!
