### ISSUE TITLE
Feature request: Check container capabilities (e.g. CAP_SYS_MODULE)

### ISSUE THREAD

**Issue by synap5e** [stealthcopter/deepce#24]
Capabilities such as CAP_SYS_MODULE allow for escapes.
It would be nice if the script ran `capsh --print` or similar and highlighted dangerous permissions, possibly with descriptions or links for found dangerous permissions.

https://0xn3va.gitbook.io/cheat-sheets/container/escaping/excessive-capabilities
https://book.hacktricks.xyz/linux-unix/privilege-escalation/docker-breakout#container-capabilities

**Comment by stealthcopter** [comment]
Thanks for the request, do you think something like this would work:

![2021-04-27_08-23](https://user-images.githubusercontent.com/1211162/116201885-e4469880-a731-11eb-9e26-9e35da56db20.png)

**Comment by synap5e** [comment]
Looks good!

**Comment by stealthcopter** [comment]
I've modified it to `Dangerous Capabilities` instead as that makes more sense. Will update it later today :)
