### ISSUE TITLE
assignment mismatch: 2 variables but scanner.Run returns 3 values

### ISSUE THREAD

**Issue by gbiagomba** [stealthcopter/deepce#38]
Hello,

I tried installing the tool on my MacBook and I got this err `cmd/gorsair.go:68:18: assignment mismatch: 2 variables but scanner.Run returns 3 values`. I looked at the code block and noticed the potential issue:
```
	results, err := scanner.Run()
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
```

I changed it to handle 3 outputs. I am only creating it here rather than apool request bc I wasn't sure if it would break anything
```
	results, _, err := scanner.Run()
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
```

**Comment by stealthcopter** [comment]
@gbiagomba I think you've got the wrong repo, there is no go code in this tool.

**Comment by gbiagomba** [comment]
@stealthcopter  whoops 😅...this is why one shouldn't code late at night tired AF. Apologies!
