### ISSUE TITLE
TryHackMe Task 2 Option 1.

### ISSUE THREAD

**Issue by ghost** [stealthcopter/deepce#9]
Hi, 

I'm just blindly following your documentation and I'm having trouble on the second task.

```
ubuntu@deepce:~$ docker cp /opt/deepce/deepce.sh alpine-container_name:/
ubuntu@deepce:~$ docker alpine-container_name exec /deepce.sh
docker: 'alpine-container_name' is not a docker command.
See 'docker --help'
ubuntu@deepce:~$ 
```

What am I doing wrong??

I know alpine-container_name Isn't the same. I changed it because I didn't want to give away an answer.

**Comment by stealthcopter** [comment]
it should be `docker exec alpine-container_name /deepce.sh`, thanks!
